version: "3.0"
services:
 nginx:
  ports:
    - "35000:80"
 proxycontainer:
  build:
   context: .
   args: 
    NODE_ENV: development
  volumes:
   - ./:/app
  environment:
   - NODE_ENV=development
  command: npm run dev