version: "3.0"
services:
 nginx:
  image: nginx:stable-alpine
  volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
 proxycontainer:
  build: .
  user: root
  depends_on:
   - mongo
   - nginx
  volumes:
   - mongo-db:/data/db
  env_file:
   - ./.env
  
 mongo:
  image: mongo
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: albertoo
    MONGO_INITDB_ROOT_PASSWORD: albertoo

volumes:
 mongo-db: